version: '3'

services:
  dass:
    image: domassistant/dass:v1
    restart: always
    privileged: true
    networks: 
      - host
    environment:
      NODE_ENV: production
      SQLITE_FILE_PATH: /var/lib/domassistant/dass-production.db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/domassistant:/var/lib/domassistant
      - /dev:/dev
    ports:
      - '80:1443'
      - '443:1443'
  watchtower:
    image: containrrr/watchtower
    restart: always
    command: --cleanup --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
